document.writeln('<table width="100%" border="0" cellspacing="0" cellpadding="3">');
document.writeln('<tr>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-664.html" target="_blank">新闻频道</a></div>');
document.writeln('<div class="list"><a href="/list-690.html" target="_blank">国内</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-689.html" target="_blank">国际</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-688.html" target="_blank">社会</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-684.html" target="_blank">经济</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-683.html" target="_blank">文化</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-682.html" target="_blank">娱乐</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-681.html" target="_blank">体育</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-680.html" target="_blank">教育</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-679.html" target="_blank">健康</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-678.html" target="_blank">生活</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-677.html" target="_blank">IT</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-676.html" target="_blank">图片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-675.html" target="_blank">视频</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-674.html" target="_blank">房产</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-673.html" target="_blank">汽车</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=694" target="_blank">图片频道</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=706" target="_blank">国内</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=705" target="_blank">国际</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=704" target="_blank">社会</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=826" target="_blank">素材</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=827" target="_blank">风景</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=828" target="_blank">美女</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=719" target="_blank">下载频道</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=733" target="_blank">Asp源码</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=732" target="_blank">.net源码</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=731" target="_blank">PHP源码</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=730" target="_blank">其它源码</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=728" target="_blank">服务器类</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=727" target="_blank">网络软件</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=726" target="_blank">应用软件</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=725" target="_blank">系统工具</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=724" target="_blank">图形图像</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=723" target="_blank">多媒体类</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=722" target="_blank">安全相关</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=720" target="_blank">硬件工具</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=736" target="_blank">网购在线</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=749" target="_blank">男鞋</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=750" target="_blank">女鞋</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=751" target="_blank">男装</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=752" target="_blank">女装</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=753" target="_blank">配饰</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=11" target="_blank">供求信息</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=583" target="_blank">工业用品</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=582" target="_blank">农林牧渔</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=580" target="_blank">生活服务</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=579" target="_blank">家居用品</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=805" target="_blank">消费品</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=844" target="_blank">房产交易</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=843" target="_blank">物品交易</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=842" target="_blank">同城交友</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=841" target="_blank">同城活动</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=840" target="_blank">商务服务</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/job" target="_blank">求职招聘</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/mnkc" target="_blank">模拟考场</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=812" target="_blank">影视频道</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=822" target="_blank">动作片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=821" target="_blank">恐怖片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=820" target="_blank">爱情片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=819" target="_blank">战争片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=818" target="_blank">喜剧片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=817" target="_blank">科幻片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=816" target="_blank">连续剧</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=815" target="_blank">综艺片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=814" target="_blank">剧情片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=813" target="_blank">纪录片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=921" target="_blank">灾难片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=920" target="_blank">武侠片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=919" target="_blank">犯罪片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=918" target="_blank">悬疑片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=917" target="_blank">冒险片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=916" target="_blank">青春片</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=915" target="_blank">高清预告</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=735" target="_blank">动漫频道</a></div>');
document.writeln('<div class="list"><a href="/Item/list.asp?id=745" target="_blank">原创漫画</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=744" target="_blank">少年热血</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=743" target="_blank">武侠格斗</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=742" target="_blank">少女爱情</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=741" target="_blank">科幻魔幻</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=740" target="_blank">竞技体育</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=739" target="_blank">爆笑喜剧</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=738" target="_blank">侦探推理</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=737" target="_blank">恐怖灵异</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-811.html" target="_blank">求职指南</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/music" target="_blank">在线听歌</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-823.html" target="_blank">资讯宝典</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-825.html" target="_blank">关于我们</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/ask" target="_blank">问答中心</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-832.html" target="_blank">帮助中心</a></div>');
document.writeln('<div class="list"><a href="/list-833.html" target="_blank">新手指南</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-838.html" target="_blank">如何付款</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-837.html" target="_blank">配送指南</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-836.html" target="_blank">帮助中心</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-835.html" target="_blank">会员服务</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-834.html" target="_blank">网站信息</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-907.html" target="_blank">简历制作</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('<tr>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-908.html" target="_blank">求职技巧</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-909.html" target="_blank">求职招聘百态</a></div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/list-911.html" target="_blank">网校名师</a></div>');
document.writeln('<div class="list"><a href="/list-912.html" target="_blank">肖秀荣</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-913.html" target="_blank">杨宗丽</a>&nbsp;<img src="/images/nl.gif" align="absmiddle">&nbsp;<a href="/list-914.html" target="_blank">韩小谦</a>&nbsp;</div>');
document.writeln('</td>');
document.writeln('<td valign="top" width="25%">');
document.writeln('<div class="classtitle" style="font-weight:bold"><img src="/images/arrow_r.gif" align="absmiddle">&nbsp;<a href="/Item/list.asp?id=924" target="_blank">二手房源</a></div>');
document.writeln('</td>');
document.writeln('</tr>');
document.writeln('</table>');
