document.writeln('<table width=\"98%\" border=\"0\" align=\"center\">')
document.writeln('<form id=\"SearchForm\" name=\"SearchForm\" method=\"get\" action=\"/plus/Search.asp\">')
document.writeln('  <tr>')
document.writeln('    <td align=\"center\"><select name=\"SearchType\">')
document.writeln('          <option value=\"1\">名 称</option>')
document.writeln('          <option value=\"2\">简 介</option>')
document.writeln('          <option value=\"3\">开发商</option>')
document.writeln('          <option value=\"4\">录入者</option>')
document.writeln('          <option value=\"5\">关键字</option>')
document.writeln('      </select>')
document.writeln('        <select name=\"ClassID\" style=\"width:150\">')
document.writeln('          <option value=\"0\" selected=\"selected\">所有栏目</option>')
document.writeln('<option value=\'20103503394691\'>ssss </option>        </select>')
document.writeln('        <input name=\"KeyWord\" type=\"text\" class=\"textbox\"  value=\"关键字\" onfocus=\"this.select();\"/>')
document.writeln('        <input name=\"ChannelID\" value=\"3\" type=\"hidden\" />')
document.writeln('        <input type=\"submit\" class=\"inputButton\" name=\"Submit\" value=\"搜 索\" /></td>')
document.writeln('  </tr>')
document.writeln('</form>')
document.writeln('</table>')
