document.writeln('<table width=\"98%\" border=\"0\" align=\"center\">')
document.writeln('<form id=\"SearchForm\" name=\"SearchForm\" method=\"get\" action=\"/plus/Search.asp\">')
document.writeln('  <tr>')
document.writeln('    <td align=\"center\"><select name=\"SearchType\">')
document.writeln('          <option value=\"1\">名 称</option>')
document.writeln('          <option value=\"2\">简 介</option>')
document.writeln('          <option value=\"3\">作 者</option>')
document.writeln('          <option value=\"4\">录入者</option>')
document.writeln('          <option value=\"5\">关键字</option>')
document.writeln('      </select>')
document.writeln('        <select name=\"ClassID\" style=\"width:150\">')
document.writeln('          <option value=\"0\" selected=\"selected\">所有栏目</option>')
document.writeln('<option value=\'20097082279507\'>图片频道 </option><option value=\'20101263240841\'>──军事 </option><option value=\'20102882145236\'>──历史 </option><option value=\'20109373476359\'>──动物 </option><option value=\'20096557476366\'>──国内 </option><option value=\'20098340362320\'>──国际 </option><option value=\'20095176599095\'>──社会 </option><option value=\'20101613104659\'>──素材 </option><option value=\'20109769073191\'>──风景 </option><option value=\'20109505856822\'>──美女 </option>        </select>')
document.writeln('        <input name=\"KeyWord\" type=\"text\" class=\"textbox\"  value=\"关键字\" onfocus=\"this.select();\"/>')
document.writeln('        <input name=\"ChannelID\" value=\"2\" type=\"hidden\" />')
document.writeln('        <input type=\"submit\" class=\"inputButton\" name=\"Submit\" value=\"搜 索\" /></td>')
document.writeln('  </tr>')
document.writeln('</form>')
document.writeln('</table>')
